services:
    postgresdb:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_USER: $POSTGRESDB_USER
            POSTGRES_PASSWORD: $POSTGRESDB_ROOT_PASSWORD
            POSTGRES_DB: $POSTGRESDB_DATABASE
        ports:
            - '$POSTGRESDB_DOCKER_PORT:$POSTGRESDB_DOCKER_PORT'
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./nurseomatordb.sql:/docker-entrypoint-initdb.d/nurseomatordb.sql

    backend:
        image: jujuguilbaud31/nurseomator:latest
        depends_on:
            - postgresdb
        build: ./../../../
        env_file: .env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        environment:
            - DB_HOST=postgresdb
            - DB_USER=$POSTGRESDB_USER
            - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
            - DB_NAME=$POSTGRESDB_DATABASE
            - DB_PORT=$POSTGRESDB_DOCKER_PORT
        stdin_open: true
        tty: true

volumes:
    postgres-data:
