version: "1.0"
services:
  api-pvra:
    container_name: "api-pvra"
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: rose
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
